# Generated by Django 4.2.5 on 2023-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_books_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Item',
        ),
    ]
