# Generated by Django 4.2.5 on 2023-09-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
