# Generated by Django 4.2.5 on 2023-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
