# Generated by Django 4.2.5 on 2023-11-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hidden',
        ),
    ]
